bin.includes = META-INF/,\
               kena.jar,\
               lib/arq-2.8.4.jar,\
               lib/iri-0.8.jar,\
               lib/jena-2.6.3.jar,\
               lib/lucene-core-2.3.1.jar,\
               lib/stax-api-1.0.1.jar,\
               lib/wstx-asl-3.2.9.jar,\
               lib/xercesImpl-2.7.1.jar,\
               lib/icu4j-71.1.jar,\
               lib/log4j-over-slf4j-2.0.17.jar
jars.compile.order = kena.jar
source.kena.jar = src/
output.kena.jar = bin/
