/*
 * This software is Copyright 2005,2006,2007,2008 Langdale Consultants.
 * Langdale Consultants can be contacted at: http://www.langdale.com.au
 */
package au.com.langdale.cimtoole.views;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IResourceChangeEvent;
import org.eclipse.core.resources.IResourceChangeListener;
import org.eclipse.core.resources.IResourceDelta;
import org.eclipse.core.resources.IWorkspaceRunnable;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.FileLocator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.jface.action.Action;
import org.eclipse.jface.action.IToolBarManager;
import org.eclipse.jface.resource.ImageDescriptor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.browser.Browser;
import org.eclipse.swt.browser.BrowserFunction;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.ui.IEditorPart;
import org.eclipse.ui.IPartListener2;
import org.eclipse.ui.IWorkbenchPage;
import org.eclipse.ui.IWorkbenchPartReference;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.browser.IWebBrowser;
import org.eclipse.ui.browser.IWorkbenchBrowserSupport;
import org.eclipse.ui.part.ViewPart;

import au.com.langdale.cimtoole.CIMToolPlugin;
import au.com.langdale.cimtoole.builder.PlantUMLRealTimePreviewBuildlet;
import au.com.langdale.cimtoole.editors.ProfileEditor;
import au.com.langdale.cimtoole.project.Info;
import au.com.langdale.util.Jobs;
import net.sourceforge.plantuml.BlockUml;
import net.sourceforge.plantuml.FileFormat;
import net.sourceforge.plantuml.FileFormatOption;
import net.sourceforge.plantuml.SourceStringReader;
import net.sourceforge.plantuml.core.DiagramDescription;
import net.sourceforge.plantuml.error.PSystemError;

/**
 * A view that displays a live PlantUML SVG rendering of the currently active
 * CIMTool profile.
 *
 * <p>
 * The rendered content is sourced from the hidden
 * {@code Profiles/.ProfileName.puml} file generated by
 * {@link PlantUMLRealTimePreviewBuildlet} whenever the profile is saved.
 *
 * <p>
 * The view provides a fully interactive SVG viewer with:
 * <ul>
 * <li>Mouse-wheel zoom centred on the cursor position.</li>
 * <li>Click-drag panning.</li>
 * <li>Zoom In, Zoom Out, Reset (1:1) and Fit-to-Window controls rendered as
 * inline SVG overlays identical in appearance to the svg-pan-zoom library used
 * by the PlantUML SVG view.</li>
 * <li>An "Open in External Browser" toolbar button.</li>
 * <li>No external CDN dependencies — all JavaScript and SVG path data is
 * inlined, making the view fully functional offline.</li>
 * </ul>
 *
 * <p>
 * Rendering uses the PlantUML library API directly via
 * {@code net.sourceforge.plantuml.library}.
 */
public class CurrentProfilePlantUmlSvgView extends ViewPart {

	public static final String VIEW_ID = "au.com.langdale.cimtoole.views.CurrentProfilePlantUmlSvgView";

	private static final String NO_PROFILE_HTML = "<html><body style='font-family:sans-serif;color:#555;padding:16px'>"
			+ "<p>No profile is currently active. Open a profile to view its diagram.</p>" + "</body></html>";

	private static final String PLANTUML_UNAVAILABLE_HTML = "<html><body style='font-family:sans-serif;color:#555;padding:16px'>"
			+ "<p>PlantUML library is not available. Install the PlantUML "
			+ "Eclipse plugin to enable diagram rendering.</p>" + "</body></html>";

	private static final String PREVIEW_UNAVAILABLE_HTML = "<html><body style='font-family:sans-serif;color:#555;padding:16px'>"
			+ "<p><b>Profile Preview Unavailable</b></p>"
			+ "<p>The profile could not be rendered as a diagram. This typically indicates "
			+ "an unusual construct or an unresolved error in the underlying profile definition.</p>"
			+ "<p>Upon resolving the issue, the diagram will render.</p>"
			+ "</body></html>";

	private Browser browser;

	/** The hidden .puml file currently being tracked and displayed. */
	private IFile currentPreviewFile;

	/** The last fully-rendered HTML — used by the external browser action. */
	private String currentHtml;

	/**
	 * Saved pan/zoom state — preserved across refreshes so the user's position and
	 * zoom level survive profile saves.
	 */
	private double savedZoom = -1;
	private double savedPanX = 0;
	private double savedPanY = 0;
	private boolean pageLoaded = false;

	/**
	 * Pending SVG content fetched by JS via the getSvgContent BrowserFunction,
	 * avoiding all string-escaping issues when passing SVG from Java to JS.
	 */
	private String pendingSvg = null;

	private IResourceChangeListener resourceListener;
	private IPartListener2 partListener;

	@Override
	public void createPartControl(Composite parent) {
		parent.setLayout(new FillLayout());
		browser = new Browser(parent, SWT.NONE);
		browser.setText(NO_PROFILE_HTML);

		// BrowserFunction that returns the pending SVG string to JavaScript.
		// Using a BrowserFunction return value avoids all JS string-escaping
		// issues with the SVG content (quotes, backslashes, newlines etc).
		new BrowserFunction(browser, "getSvgContent") {
			@Override
			public Object function(Object[] args) {
				return pendingSvg != null ? pendingSvg : "";
			}
		};

		// Register a BrowserFunction that JavaScript calls just before each
		// refresh to save the current pan/zoom state back into Java fields.
		new BrowserFunction(browser, "saveViewState") {
			@Override
			public Object function(Object[] args) {
				if (args != null && args.length == 3) {
					savedZoom = ((Number) args[0]).doubleValue();
					savedPanX = ((Number) args[1]).doubleValue();
					savedPanY = ((Number) args[2]).doubleValue();
				}
				return null;
			}
		};

		// Adding an "Open in External Browser" action to basically serve
		// as an equivalent button to what the PlantUmlSvgView has.
		IToolBarManager toolBar = getViewSite().getActionBars().getToolBarManager();
		toolBar.add(new Action("Open in external browser",
				ImageDescriptor.createFromFile(CurrentProfilePlantUmlSvgView.class, "/icons/external_browser.png")) {
			@Override
			public void run() {
				openInExternalBrowser();
			}
		});

		registerResourceListener();
		registerPartListener();

		// Seed from whatever profile editor is already active.
		IWorkbenchPage page = getSite().getPage();
		if (page != null) {
			IEditorPart active = page.getActiveEditor();
			if (active instanceof ProfileEditor) {
				handleProfileEditorActivated((ProfileEditor) active);
			}
		}
	}

	@Override
	public void setFocus() {
		if (browser != null && !browser.isDisposed())
			browser.setFocus();
	}

	@Override
	public void dispose() {
		if (resourceListener != null) {
			ResourcesPlugin.getWorkspace().removeResourceChangeListener(resourceListener);
			resourceListener = null;
		}
		if (partListener != null && getSite() != null && getSite().getPage() != null) {
			getSite().getPage().removePartListener(partListener);
			partListener = null;
		}
		super.dispose();
	}

	private void openInExternalBrowser() {
		if (currentHtml == null)
			return;
		try {
			Path tmp = Files.createTempFile("cimtool-preview-", ".html");
			Files.write(tmp, currentHtml.getBytes(StandardCharsets.UTF_8));
			IWorkbenchBrowserSupport support = PlatformUI.getWorkbench().getBrowserSupport();
			IWebBrowser extBrowser = support.getExternalBrowser();
			extBrowser.openURL(tmp.toUri().toURL());
		} catch (Exception e) {
			CIMToolPlugin.getDefault().getLog().error("Failed to open preview in external browser", e);
		}
	}

	private void registerResourceListener() {
		resourceListener = event -> {
			if (event.getType() != IResourceChangeEvent.POST_CHANGE || currentPreviewFile == null)
				return;
			IResourceDelta delta = event.getDelta().findMember(currentPreviewFile.getFullPath());
			if (delta != null && (delta.getFlags() & (IResourceDelta.CONTENT | IResourceDelta.REPLACED)) != 0) {
				scheduleRefresh();
			}
		};
		ResourcesPlugin.getWorkspace().addResourceChangeListener(resourceListener, IResourceChangeEvent.POST_CHANGE);
	}

	private void registerPartListener() {
		partListener = new IPartListener2() {
			@Override
			public void partActivated(IWorkbenchPartReference ref) {
				IWorkbenchPage page = getSite().getPage();
				if (page == null)
					return;
				IEditorPart editor = page.getActiveEditor();
				if (editor instanceof ProfileEditor)
					handleProfileEditorActivated((ProfileEditor) editor);
			}

			@Override
			public void partBroughtToTop(IWorkbenchPartReference r) {
			}

			@Override
			public void partClosed(IWorkbenchPartReference r) {
			}

			@Override
			public void partDeactivated(IWorkbenchPartReference r) {
			}

			@Override
			public void partHidden(IWorkbenchPartReference r) {
			}

			@Override
			public void partInputChanged(IWorkbenchPartReference r) {
			}

			@Override
			public void partOpened(IWorkbenchPartReference r) {
			}

			@Override
			public void partVisible(IWorkbenchPartReference r) {
			}
		};
		getSite().getPage().addPartListener(partListener);
	}

	private void handleProfileEditorActivated(ProfileEditor editor) {
		IFile owlFile = editor.getFile();
		if (owlFile == null)
			return;

		IFolder profileFolder = Info.getProfileFolder(owlFile.getProject());
		if (profileFolder == null || !profileFolder.exists())
			return;

		String baseName = owlFile.getName().replaceFirst("\\.[^.]+$", "");
		IFile previewFile = profileFolder.getFile("." + baseName + "." + PlantUMLRealTimePreviewBuildlet.PREVIEW_EXT);

		boolean previewFileChanged = !previewFile.equals(currentPreviewFile);
		if (previewFileChanged) {
			// Reset saved state and page when switching profiles so the new
			// diagram fits to window and reloads the page fresh.
			savedZoom = -1;
			savedPanX = 0;
			savedPanY = 0;
			pageLoaded = false;
		}
		currentPreviewFile = previewFile;

		Display display = getSite().getShell().getDisplay();
		display.asyncExec(() -> {
			if (browser != null && !browser.isDisposed())
				setPartName(owlFile.getName() + " Preview");
		});

		if (previewFileChanged) {
			// Always regenerate the hidden .puml file when switching to a different
			// profile editor — this ensures the current preferences (including any
			// project- or profile-level overrides) are applied, so stale content
			// from a previous style is never displayed. The IResourceChangeListener
			// will trigger scheduleRefresh() once the file is written.
			IWorkspaceRunnable runnable = new PlantUMLRealTimePreviewBuildlet().asRunnable(previewFile, false);
			// Use the project as the scheduling rule (not just profileFolder) so
			// that inner workspace operations on the Schema folder — acquired by
			// Task.getBackgroundModel() during build — do not violate the rule
			// nesting constraint (Schema is not a child of Profiles).
			Jobs.runJob(runnable, owlFile.getProject(), "Regenerating real-time preview diagram");
		}
	}

	private void scheduleRefresh() {
		Display.getDefault().asyncExec(() -> {
			if (browser != null && !browser.isDisposed())
				refresh();
		});
	}

	private void refresh() {
		if (currentPreviewFile == null || !currentPreviewFile.exists()) {
			currentHtml = null;
			pageLoaded = false;
			browser.setText(NO_PROFILE_HTML);
			return;
		}

		String pumlContent = readFile(currentPreviewFile);
		if (pumlContent == null || pumlContent.isEmpty()) {
			currentHtml = null;
			pageLoaded = false;
			browser.setText(NO_PROFILE_HTML);
			return;
		}

		RenderResult result = renderProfile(pumlContent);
		if (result.status == RenderResult.Status.PARSE_ERROR) {
			CIMToolPlugin.getDefault().getLog().warn("PlantUML preview unavailable for "
					+ currentPreviewFile.getFullPath()
					+ ": the generated .puml source produced a parse-error diagram");
			currentHtml = null;
			pageLoaded = false;
			browser.setText(PREVIEW_UNAVAILABLE_HTML);
			return;
		}
		if (result.status == RenderResult.Status.UNAVAILABLE) {
			currentHtml = null;
			pageLoaded = false;
			browser.setText(PLANTUML_UNAVAILABLE_HTML);
			return;
		}

		String svg = result.svg;
		if (pageLoaded) {
			// Page is already loaded — capture current state then update the SVG
			// in-place via JavaScript. This avoids any page reload and eliminates
			// the flash entirely.
			browser.execute("if(window.zoomPlantuml){" + "saveViewState(window.zoomPlantuml.getZoom(),"
					+ "window.zoomPlantuml.getPan().x," + "window.zoomPlantuml.getPan().y);}");
			updateSvgInPlace(svg);
			// Keep currentHtml in sync so the external browser always
			// opens the latest rendered version, not the stale first load.
			currentHtml = buildInteractiveHtml(svg);
		} else {
			// First load — set the full page.
			currentHtml = buildInteractiveHtml(svg);
			browser.setText(currentHtml);
			pageLoaded = true;
		}
	}

	/**
	 * Builds a fully self-contained, offline-capable HTML page wrapping the given
	 * SVG with pan, zoom, and fit-to-window controls.
	 *
	 * <p>
	 * The control overlay uses the exact same SVG path geometry as the svg-pan-zoom
	 * library used by the PlantUML SVG view — semi-transparent circular buttons
	 * with the same stroke weight and colour — so the two views have a visually
	 * consistent look and feel.
	 *
	 * <p>
	 * No external scripts or stylesheets are referenced. All JavaScript and SVG
	 * markup is inlined in the returned string.
	 */
	/**
	 * Builds a fully self-contained HTML page wrapping the given SVG with pan,
	 * zoom, fit and reset controls via the svg-pan-zoom library, matching the
	 * PlantUML Eclipse plugin's interactive-svg-template.mustache exactly. The
	 * svg-pan-zoom library is loaded from the bundled {@code js/svg-pan-zoom.js}
	 * file so no internet connection is required.
	 */
	private void updateSvgInPlace(String svg) {
		// Store SVG so getSvgContent() BrowserFunction can return it to JS.
		// This completely avoids JS string-escaping issues with SVG content.
		pendingSvg = svg;

		StringBuilder js = new StringBuilder();
		js.append("(function(){");
		// Destroy existing svgPanZoom instance
		js.append("if(window.zoomPlantuml){window.zoomPlantuml.destroy();window.zoomPlantuml=null;}");
		// Fetch SVG from Java via BrowserFunction — no escaping needed
		js.append("var svgStr=getSvgContent();");
		// Parse the SVG string safely using DOMParser
		js.append("var doc=new DOMParser().parseFromString(svgStr,'image/svg+xml');");
		js.append("var newSvg=doc.documentElement;");
		// Replace the existing SVG element
		js.append("var el=document.getElementById('plantuml');");
		js.append("if(el&&newSvg){el.parentNode.replaceChild(newSvg,el);}");
		// Re-initialise svgPanZoom
		js.append("window.zoomPlantuml=svgPanZoom('#plantuml',{");
		js.append("zoomEnabled:true,controlIconsEnabled:true,");
		if (savedZoom > 0) {
			js.append("fit:false,center:false});");
			js.append("window.zoomPlantuml.zoom(" + savedZoom + ");");
			js.append("window.zoomPlantuml.pan({x:" + savedPanX + ",y:" + savedPanY + "});");
		} else {
			js.append("fit:true,center:true});");
		}
		js.append("})()");
		browser.execute(js.toString());
	}

	private String buildInteractiveHtml(String svg) {
		String scriptUrl = getSvgPanZoomUrl();
		StringBuilder sb = new StringBuilder(svg.length() + 4096);
		sb.append("<html>\n");
		sb.append("  <head>\n");
		sb.append("    <script src=\"").append(scriptUrl).append("\"></script>\n");
		sb.append("    <style type=\"text/css\" media=\"screen\">\n");
		sb.append("      svg {\n");
		sb.append("        display:block; position:absolute;\n");
		sb.append("        width:100% !important; height:100% !important;\n");
		sb.append("      }\n");
		sb.append("      body { opacity:0; }\n");
		sb.append("    </style>\n");
		sb.append("  </head>\n");
		sb.append("  <body>\n");
		sb.append("    ").append(svg).append("\n");
		sb.append("    <script>\n");
		sb.append("      window.onload = function() {\n");
		sb.append("        window.zoomPlantuml = svgPanZoom('#plantuml', {\n");
		sb.append("          zoomEnabled: true,\n");
		sb.append("          controlIconsEnabled: true,\n");
		// If we have saved state, disable fit/center so svgPanZoom does not
		// snap to the default view before we restore — eliminating the flash.
		sb.append("          fit: " + (savedZoom <= 0 ? "true" : "false") + ",\n");
		sb.append("          center: " + (savedZoom <= 0 ? "true" : "false") + ",\n");
		sb.append("        });\n");
		if (savedZoom > 0) {
			sb.append("        window.zoomPlantuml.zoom(" + savedZoom + ");\n");
			sb.append("        window.zoomPlantuml.pan({x:" + savedPanX + ",y:" + savedPanY + "});\n");
		}
		sb.append("        document.body.style.opacity = '1';\n");
		sb.append("      };\n");
		sb.append("    </script>\n");
		sb.append("  </body>\n");
		sb.append("</html>\n");
		return sb.toString();
	}

	/**
	 * Returns a file:// URL pointing to the bundled svg-pan-zoom.js so the SWT
	 * Browser can load it without any internet connection.
	 */
	private String getSvgPanZoomUrl() {
		try {
			java.net.URL url = FileLocator
					.toFileURL(Platform.getBundle(CIMToolPlugin.PLUGIN_ID).getEntry("js/svg-pan-zoom.js"));
			return url.toString();
		} catch (Exception e) {
			CIMToolPlugin.getDefault().getLog().error("Could not resolve svg-pan-zoom.js URL", e);
			// Fallback to the CDN URL used by the PlantUML Eclipse plugin
			return "https://bumbu.github.io/svg-pan-zoom/dist/svg-pan-zoom.min.js";
		}
	}

	private String readFile(IFile file) {
		// Read directly from the filesystem, bypassing the Eclipse workspace
		// cache, to guarantee we see the latest written content.
		try {
			byte[] bytes = Files.readAllBytes(Paths.get(file.getLocation().toOSString()));
			// Strip UTF-8 BOM if present so PlantUML sees a clean @startuml.
			if (bytes.length >= 3 && (bytes[0] & 0xFF) == 0xEF && (bytes[1] & 0xFF) == 0xBB
					&& (bytes[2] & 0xFF) == 0xBF) {
				return new String(bytes, 3, bytes.length - 3, StandardCharsets.UTF_8);
			}
			return new String(bytes, StandardCharsets.UTF_8);
		} catch (IOException e) {
			CIMToolPlugin.getDefault().getLog().error(e.getMessage(), e);
			return null;
		}
	}

	/**
	 * Three-state outcome from {@link #renderProfile(String)}.
	 *
	 * <p>
	 * Distinguishes a successful render from the two failure modes the caller
	 * needs to react to differently:
	 * <ul>
	 * <li>{@link Status#SUCCESS} — the {@code .puml} source parsed and rendered
	 * cleanly; {@link #svg} holds the cleaned SVG markup ready to inject.</li>
	 * <li>{@link Status#PARSE_ERROR} — the {@code .puml} source parsed as an
	 * error diagram (PlantUML's {@code PSystemError}). The user should see the
	 * {@link CurrentProfilePlantUmlSvgView#PREVIEW_UNAVAILABLE_HTML} placeholder
	 * rather than PlantUML's source-listing error SVG.</li>
	 * <li>{@link Status#UNAVAILABLE} — the PlantUML library itself failed or
	 * returned no usable output (library missing, exception thrown, empty
	 * description). The user should see the
	 * {@link CurrentProfilePlantUmlSvgView#PLANTUML_UNAVAILABLE_HTML}
	 * placeholder.</li>
	 * </ul>
	 */
	private static final class RenderResult {
		enum Status {
			SUCCESS, PARSE_ERROR, UNAVAILABLE
		}

		final Status status;
		final String svg;

		private RenderResult(Status status, String svg) {
			this.status = status;
			this.svg = svg;
		}

		static RenderResult success(String svg) {
			return new RenderResult(Status.SUCCESS, svg);
		}

		static RenderResult error() {
			return new RenderResult(Status.PARSE_ERROR, null);
		}

		static RenderResult unavailable() {
			return new RenderResult(Status.UNAVAILABLE, null);
		}
	}

	/**
	 * Parses and renders a {@code .puml} source string, returning a
	 * {@link RenderResult} that distinguishes successful rendering, a PlantUML
	 * parse error, and library unavailability.
	 *
	 * <p>
	 * Before invoking the renderer, the parsed block is inspected via
	 * {@link SourceStringReader#getBlocks()} and checked for
	 * {@link PSystemError}. When PlantUML cannot parse the input, it normally
	 * produces an "error diagram" — a syntax-highlighted listing of the offending
	 * source with the error region called out. That output is unhelpful in the
	 * CIMTool preview context (the user did not author the {@code .puml}; it was
	 * machine-generated from their profile), so we detect the error state up
	 * front and return {@link RenderResult.Status#PARSE_ERROR} without invoking
	 * the renderer at all.
	 *
	 * <p>
	 * {@code PLANTUML_SECURITY_PROFILE} is set to {@code SANDBOX} for the duration
	 * of this call and then restored to its previous value in the {@code finally}
	 * block. {@code SANDBOX} is sufficient for CIMTool's use case because the
	 * {@code .puml} files rendered here are machine-generated by
	 * {@link PlantUMLRealTimePreviewBuildlet} from the user's own profile data via a
	 * controlled XSLT transform — they contain only class and relationship
	 * declarations with no {@code !include} directives, remote URLs, or preprocessor
	 * macros that would require broader access.
	 *
	 * <p>
	 * The property is scoped to this call rather than set globally to avoid
	 * affecting other PlantUML rendering in the same JVM — notably the Asciidoctor
	 * Eclipse plugin's PlantUML integration, which may require less restrictive
	 * access for its own rendering operations.
	 *
	 * <p>
	 * There are five supported values in order from most permissive to most
	 * restrictive:
	 * <p>
	 * UNSECURE: full access to local files, environment variables, and all URLs.
	 * <p>
	 * LEGACY: the default prior to v1.2020.11, emulating older PlantUML behaviour.
	 * Slightly more restricted than UNSECURE but broadly permissive. Being phased
	 * out.
	 * <p>
	 * INTERNET: no access to local files, but all URLs on ports 80 and 443 are
	 * accessible. The recommended minimum for server deployments. Default for the
	 * PlantUML server.
	 * <p>
	 * ALLOWLIST: no access to local files or URLs unless explicitly listed via
	 * {@code plantuml.allowlist.path}, {@code plantuml.include.path}, and
	 * {@code plantuml.allowlist.url} properties.
	 * <p>
	 * SANDBOX: completely locked down. No local file or URL access whatsoever,
	 * allowlists are ignored. This is what CIMTool uses since the generated
	 * {@code .puml} content requires no external access.
	 */
	private RenderResult renderProfile(String pumlSource) {
		String previousProfile = System.getProperty("PLANTUML_SECURITY_PROFILE");
		try {
			System.setProperty("PLANTUML_SECURITY_PROFILE", "SANDBOX");

			SourceStringReader reader = new SourceStringReader(pumlSource);

			// Inspect the parsed block before rendering. If PlantUML produced an
			// error diagram, skip rendering entirely — we do not want to display
			// PlantUML's source-listing error SVG to the user.
			List<BlockUml> blocks = reader.getBlocks();
			if (blocks != null && !blocks.isEmpty() && blocks.get(0).getDiagram() instanceof PSystemError) {
				return RenderResult.error();
			}

			ByteArrayOutputStream svgOut = new ByteArrayOutputStream();
			DiagramDescription desc = reader.outputImage(svgOut, 0, new FileFormatOption(FileFormat.SVG));
			svgOut.flush();

			if (desc == null)
				return RenderResult.unavailable();
			String description = desc.getDescription();
			if (description == null || description.isEmpty())
				return RenderResult.unavailable();

			return RenderResult.success(cleanSvg(svgOut.toString(StandardCharsets.UTF_8.name())));
		} catch (Exception e) {
			CIMToolPlugin.getDefault().getLog().error("Failed to render preview .puml as SVG", e);
			return RenderResult.unavailable();
		} finally {
	        if (previousProfile != null)
	            System.setProperty("PLANTUML_SECURITY_PROFILE", previousProfile);
	        else
	            System.clearProperty("PLANTUML_SECURITY_PROFILE");
	    }
	}

	/**
	 * Strips the {@code <?xml...?>} declaration and adds {@code id='plantuml'} to
	 * the root {@code <svg>} element, matching the logic in the PlantUML Eclipse
	 * plugin's {@code AbstractSvg2HtmlConverter.cleanSvg()}.
	 */
	private String cleanSvg(String svg) {
		if (svg.trim().startsWith("<?xml"))
			svg = svg.substring(svg.indexOf("?>") + 2);
		String svgTag = "<svg";
		int pos = svg.indexOf(svgTag);
		if (pos >= 0) {
			svg = svg.substring(0, pos) + svgTag + " id='plantuml'" + svg.substring(pos + svgTag.length());
		}
		return svg;
	}
}